// GENERADO — no editar a mano.
// Fuente: data/catalogo/topics.json (snapshot F0-05, tabla `topics` real).
// Regenerar: node scripts/gen-topics-catalog.mjs (desde frontend/), tras cambiar el catálogo,
// y commitear el resultado — mismo criterio que el resto del catálogo-como-código.
// Generado: 2026-07-13 · 99 tópicos activos.
// Listado LIVIANO (sin prosa) — usa esto Topics.tsx (eager). El contenido completo esta en topicsCatalog.generated.ts (lazy, solo TopicDetail).

export interface TopicIndexEntry {
  id: number
  slug: string
  title: string
  category: string
  categoryLabel: string
  audience: 'adult' | 'kid'
  segmento: string
  levels: ReadonlyArray<string>
  /** Hasta 6 keywords reales del tópico (composer_proto usa keywords[:6]). */
  keywords: ReadonlyArray<string>
}

export const TOPICS_INDEX: ReadonlyArray<TopicIndexEntry> = [
  {
    id: 3,
    slug: 'ableton-produccion',
    title: 'Producción musical y cultura DJ',
    category: 'musica',
    categoryLabel: 'Música',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['B1', 'B2', 'C1', 'C2'],
    keywords: ['I usually start with', 'the trick is', 'play around with', 'happy accident', 'the sound I was after', 'tweak'],
  },
  {
    id: 4,
    slug: 'ia-etica',
    title: 'IA generativa · ética',
    category: 'tech',
    categoryLabel: 'Tecnología',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    keywords: ['double-edged sword', 'we should be careful with', 'hard to draw the line', 'happening faster than we think', 'I\'m not sure how I feel about', 'useful but scary'],
  },
  {
    id: 5,
    slug: 'fuerza-powerlifting',
    title: 'Entrenamiento de fuerza y suplementación',
    category: 'fitness',
    categoryLabel: 'Fitness y entrenamiento',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A2', 'B1', 'B2', 'C1'],
    keywords: ['hit a PR', 'felt amazing', 'back day', 'form over weight', 'took years to', 'small wins'],
  },
  {
    id: 9,
    slug: 'futbol-mundial',
    title: 'Fútbol · Mundiales y selecciones',
    category: 'deportes',
    categoryLabel: 'Deportes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    keywords: ['amazing match', 'comeback', 'couldn\'t believe it', 'the best game I\'ve ever seen', 'we deserved it', 'robbed'],
  },
  {
    id: 15,
    slug: 'asado-argentino',
    title: 'Asado argentino · técnica y rituales',
    category: 'gastronomia',
    categoryLabel: 'Gastronomía',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    keywords: ['takes hours', 'the smell', 'Sunday tradition', 'low and slow', 'perfectly cooked', 'everyone gathers around'],
  },
  {
    id: 17,
    slug: 'espacio-astronomia',
    title: 'Espacio · astronomía y misiones',
    category: 'ciencia',
    categoryLabel: 'Ciencia',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    keywords: ['mind-blowing', 'imagine that', 'I read recently that', 'we still don\'t know', 'tiny in comparison', 'it took years'],
  },
  {
    id: 18,
    slug: 'clima-cambio',
    title: 'Cambio climático · ciencia y políticas',
    category: 'ciencia',
    categoryLabel: 'Ciencia',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    keywords: ['we\'re running out of', 'small changes add up', 'I\'m worried about', 'we should be doing more', 'the data shows', 'it\'s already affecting'],
  },
  {
    id: 20,
    slug: 'series-streaming',
    title: 'Series de streaming · drama prestigio',
    category: 'entretenimiento',
    categoryLabel: 'Entretenimiento',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    keywords: ['binged it', 'hooked from episode one', 'slow burn', 'the writing', 'the ending broke me', 'underrated'],
  },
  {
    id: 21,
    slug: 'videojuegos-aaa',
    title: 'Videojuegos · indie y AAA',
    category: 'entretenimiento',
    categoryLabel: 'Entretenimiento',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    keywords: ['addictive', 'playing through', 'the story really got me', 'couldn\'t put it down', 'underrated gem', 'the gameplay just feels right'],
  },
  {
    id: 23,
    slug: 'stand-up-comedia',
    title: 'Stand-up · comediantes y especiales',
    category: 'entretenimiento',
    categoryLabel: 'Entretenimiento',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    keywords: ['had me crying laughing', 'spot on', 'uncomfortable but funny', 'the way he tells it', 'edgy', 'relatable'],
  },
  {
    id: 24,
    slug: 'meditacion-mindfulness',
    title: 'Meditación y mindfulness',
    category: 'lifestyle',
    categoryLabel: 'Estilo de vida',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    keywords: ['helps me', 'calms me down', 'I try to', 'every morning', 'took a while to', 'I noticed that'],
  },
  {
    id: 25,
    slug: 'nutricion-dietas',
    title: 'Nutrición · dietas y mitos',
    category: 'lifestyle',
    categoryLabel: 'Estilo de vida',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    keywords: ['I try to stick to', 'made a huge difference', 'not as hard as it sounds', 'I cut down on', 'energy levels', 'small changes'],
  },
  {
    id: 27,
    slug: 'remoto-nomada',
    title: 'Trabajo remoto · nómade digital',
    category: 'negocios',
    categoryLabel: 'Negocios y carrera',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    keywords: ['best of both worlds', 'I miss the office sometimes', 'flexible', 'discipline is key', 'I work better when', 'the freedom'],
  },
  {
    id: 30,
    slug: 'japon-cultura',
    title: 'Japón · cultura y tradiciones',
    category: 'viajes',
    categoryLabel: 'Viajes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    keywords: ['blew me away', 'completely different vibe', 'I\'d go back tomorrow', 'the food alone', 'wish I had more time', 'every detail'],
  },
  {
    id: 31,
    slug: 'patagonia-trekking',
    title: 'Patagonia · trekking y montañas',
    category: 'viajes',
    categoryLabel: 'Viajes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    keywords: ['the silence up there', 'tougher than I expected', 'worth every step', 'weather changed in minutes', 'stunning view', 'couldn\'t believe my eyes'],
  },
  {
    id: 32,
    slug: 'ciudades-que-quiero-conocer',
    title: 'Ciudades que quiero conocer',
    category: 'viajes',
    categoryLabel: 'Viajes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2'],
    keywords: [],
  },
  {
    id: 33,
    slug: 'musica-mi-banda-favorita',
    title: 'Mi banda favorita',
    category: 'musica',
    categoryLabel: 'Música',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['band', 'favorite', 'discover', 'lyrics', 'album', 'concert'],
  },
  {
    id: 34,
    slug: 'musica-conciertos-marcaron',
    title: 'Conciertos que me marcaron',
    category: 'musica',
    categoryLabel: 'Música',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['concert', 'live', 'crowd', 'venue', 'encore', 'energy'],
  },
  {
    id: 36,
    slug: 'musica-aprender-instrumento',
    title: 'Aprender un instrumento',
    category: 'musica',
    categoryLabel: 'Música',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['instrument', 'practice', 'chords', 'scales', 'lesson', 'self-taught'],
  },
  {
    id: 39,
    slug: 'musica-emociones',
    title: 'Música y emociones',
    category: 'musica',
    categoryLabel: 'Música',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['mood', 'nostalgia', 'tear', 'soundtrack of my life', 'evoke', 'associate'],
  },
  {
    id: 41,
    slug: 'peliculas-mi-favorita',
    title: 'Una peli que me marcó',
    category: 'entretenimiento',
    categoryLabel: 'Entretenimiento',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['movie', 'favorite', 'plot', 'twist', 'character', 'scene'],
  },
  {
    id: 44,
    slug: 'peliculas-libro-vs-pelicula',
    title: 'Libro vs película',
    category: 'entretenimiento',
    categoryLabel: 'Entretenimiento',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['adaptation', 'loyal', 'miss the point', 'casting', 'purist', 'skip'],
  },
  {
    id: 46,
    slug: 'peliculas-cine-streaming',
    title: 'Cine vs streaming en casa',
    category: 'entretenimiento',
    categoryLabel: 'Entretenimiento',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['cinema', 'theater', 'release', 'experience', 'couch', 'popcorn'],
  },
  {
    id: 47,
    slug: 'peliculas-generos',
    title: 'Géneros que evito y por qué',
    category: 'entretenimiento',
    categoryLabel: 'Entretenimiento',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['genre', 'horror', 'drama', 'romcom', 'thriller', 'documentary'],
  },
  {
    id: 49,
    slug: 'deportes-mi-deporte',
    title: 'Mi deporte favorito',
    category: 'deportes',
    categoryLabel: 'Deportes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['sport', 'play', 'watch', 'team', 'league', 'rookie'],
  },
  {
    id: 50,
    slug: 'deportes-equipo',
    title: 'Mi equipo y sus rivales',
    category: 'deportes',
    categoryLabel: 'Deportes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['team', 'rival', 'fan base', 'derby', 'home', 'away'],
  },
  {
    id: 51,
    slug: 'deportes-partido-inolvidable',
    title: 'Un partido inolvidable',
    category: 'deportes',
    categoryLabel: 'Deportes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['match', 'comeback', 'extra time', 'penalty', 'underdog', 'final whistle'],
  },
  {
    id: 52,
    slug: 'deportes-idolos',
    title: 'Ídolos del deporte',
    category: 'deportes',
    categoryLabel: 'Deportes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['idol', 'GOAT', 'legend', 'career', 'retire', 'comeback'],
  },
  {
    id: 57,
    slug: 'videojuegos-juego-momento',
    title: 'El juego del momento',
    category: 'entretenimiento',
    categoryLabel: 'Entretenimiento',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['game', 'playthrough', 'addicting', 'save', 'level up', 'grinding'],
  },
  {
    id: 59,
    slug: 'videojuegos-multiplayer',
    title: 'Jugar con amigos online',
    category: 'entretenimiento',
    categoryLabel: 'Entretenimiento',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['multiplayer', 'co-op', 'voice chat', 'lobby', 'lag', 'toxic'],
  },
  {
    id: 65,
    slug: 'comida-mi-favorita',
    title: 'Mi comida favorita',
    category: 'comida',
    categoryLabel: 'Comida y bebida',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['food', 'dish', 'favorite', 'taste', 'smell', 'homemade'],
  },
  {
    id: 66,
    slug: 'comida-cocinar-casa',
    title: 'Cocinar en casa',
    category: 'comida',
    categoryLabel: 'Comida y bebida',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['cook', 'kitchen', 'ingredient', 'recipe', 'stove', 'oven'],
  },
  {
    id: 69,
    slug: 'comida-tipica-pais',
    title: 'Comida típica de mi país',
    category: 'comida',
    categoryLabel: 'Comida y bebida',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['traditional', 'national dish', 'regional', 'comfort food', 'Sunday lunch', 'festival'],
  },
  {
    id: 71,
    slug: 'comida-cocinar-otros',
    title: 'Cocinar para otros',
    category: 'comida',
    categoryLabel: 'Comida y bebida',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['host', 'guest', 'dinner party', 'impress', 'show off', 'stress'],
  },
  {
    id: 73,
    slug: 'animales-mi-mascota',
    title: 'Mi mascota',
    category: 'animales',
    categoryLabel: 'Animales',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['pet', 'dog', 'cat', 'adopt', 'rescue', 'habits'],
  },
  {
    id: 74,
    slug: 'animales-raros',
    title: 'Animales raros que existen',
    category: 'animales',
    categoryLabel: 'Animales',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A2', 'B1', 'B2', 'C1'],
    keywords: ['bizarre', 'deep sea', 'platypus', 'axolotl', 'blobfish', 'documentary'],
  },
  {
    id: 76,
    slug: 'animales-peligro-extincion',
    title: 'Animales en peligro',
    category: 'animales',
    categoryLabel: 'Animales',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A2', 'B1', 'B2', 'C1'],
    keywords: ['endangered', 'extinct', 'habitat', 'conservation', 'poaching', 'captivity'],
  },
  {
    id: 81,
    slug: 'viajes-ultimo-viaje',
    title: 'Mi último viaje',
    category: 'viajes',
    categoryLabel: 'Viajes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['trip', 'destination', 'highlight', 'weather', 'local', 'flight'],
  },
  {
    id: 82,
    slug: 'viajes-sonado',
    title: 'Mi viaje soñado',
    category: 'viajes',
    categoryLabel: 'Viajes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['dream', 'bucket list', 'someday', 'save up', 'plan', 'destination'],
  },
  {
    id: 83,
    slug: 'viajes-mochilero',
    title: 'Mochilero vs hotel',
    category: 'viajes',
    categoryLabel: 'Viajes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A2', 'B1', 'B2', 'C1'],
    keywords: ['backpacker', 'hostel', 'luxury', 'hotel', 'off the beaten path', 'spend'],
  },
  {
    id: 84,
    slug: 'viajes-choque-cultural',
    title: 'Choque cultural',
    category: 'viajes',
    categoryLabel: 'Viajes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['culture shock', 'weird', 'rude', 'polite', 'unspoken', 'adapt'],
  },
  {
    id: 85,
    slug: 'viajes-comida-en-viajes',
    title: 'Comer cuando viajás',
    category: 'viajes',
    categoryLabel: 'Viajes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['street food', 'fancy', 'Michelin', 'scared', 'adventurous', 'weird'],
  },
  {
    id: 86,
    slug: 'viajes-solo',
    title: 'Viajar solo',
    category: 'viajes',
    categoryLabel: 'Viajes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['solo', 'alone', 'lonely', 'freedom', 'introvert', 'meet people'],
  },
  {
    id: 87,
    slug: 'viajes-turismo-masivo',
    title: 'Turismo masivo y sus efectos',
    category: 'viajes',
    categoryLabel: 'Viajes',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['B1', 'B2', 'C1'],
    keywords: ['overtourism', 'destination', 'ruined', 'local', 'Airbnb effect', 'gentrification'],
  },
  {
    id: 88,
    slug: 'tech-apps-diarias',
    title: 'Apps que uso a diario',
    category: 'tech',
    categoryLabel: 'Tecnología',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['app', 'daily', 'habit', 'addicted', 'notification', 'swipe'],
  },
  {
    id: 89,
    slug: 'tech-inteligencia-artificial',
    title: 'Inteligencia artificial',
    category: 'tech',
    categoryLabel: 'Tecnología',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['AI', 'ChatGPT', 'generate', 'replace', 'job', 'creative'],
  },
  {
    id: 90,
    slug: 'tech-privacidad',
    title: 'Privacidad online',
    category: 'tech',
    categoryLabel: 'Tecnología',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['B1', 'B2', 'C1'],
    keywords: ['privacy', 'data', 'tracking', 'cookie', 'VPN', 'creepy'],
  },
  {
    id: 91,
    slug: 'tech-gadget-cambio-vida',
    title: 'Un gadget que me cambió la vida',
    category: 'tech',
    categoryLabel: 'Tecnología',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['gadget', 'device', 'game-changer', 'essential', 'luxury', 'splurge'],
  },
  {
    id: 92,
    slug: 'tech-aprender-codear',
    title: 'Aprender a programar',
    category: 'tech',
    categoryLabel: 'Tecnología',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['code', 'programming', 'learn', 'tutorial', 'bootcamp', 'self-taught'],
  },
  {
    id: 93,
    slug: 'tech-futuro-trabajo',
    title: 'IA y el futuro del trabajo',
    category: 'tech',
    categoryLabel: 'Tecnología',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['B1', 'B2', 'C1'],
    keywords: ['automation', 'job loss', 'skill', 'reskill', 'creative', 'manual'],
  },
  {
    id: 94,
    slug: 'tech-adiccion-celular',
    title: 'Adicción al celular',
    category: 'tech',
    categoryLabel: 'Tecnología',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['B1', 'B2', 'C1'],
    keywords: ['screen time', 'addicted', 'doomscroll', 'limit', 'notification', 'dopamine'],
  },
  {
    id: 96,
    slug: 'ciencia-curiosidad',
    title: 'Una curiosidad científica',
    category: 'ciencia',
    categoryLabel: 'Ciencia',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['fact', 'mind-blown', 'phenomenon', 'explain', 'physics', 'biology'],
  },
  {
    id: 104,
    slug: 'arte-artista-admiro',
    title: 'Un artista que admiro',
    category: 'arte',
    categoryLabel: 'Arte',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['artist', 'admire', 'work', 'style', 'influence', 'discover'],
  },
  {
    id: 108,
    slug: 'arte-crear-propio',
    title: 'Crear arte propio',
    category: 'arte',
    categoryLabel: 'Arte',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['create', 'hobby', 'amateur', 'draw', 'paint', 'write'],
  },
  {
    id: 112,
    slug: 'fitness-rutina-actual',
    title: 'Mi rutina actual',
    category: 'fitness',
    categoryLabel: 'Fitness y entrenamiento',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['routine', 'gym', 'morning', 'evening', 'consistent', 'skip'],
  },
  {
    id: 113,
    slug: 'fitness-empezar-entrenar',
    title: 'Empezar a entrenar',
    category: 'fitness',
    categoryLabel: 'Fitness y entrenamiento',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['start', 'intimidating', 'newbie', 'personal trainer', 'form', 'consistency'],
  },
  {
    id: 116,
    slug: 'fitness-salud-mental',
    title: 'Salud mental',
    category: 'fitness',
    categoryLabel: 'Fitness y entrenamiento',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['mental health', 'therapy', 'anxious', 'stress', 'burnout', 'talk to'],
  },
  {
    id: 120,
    slug: 'moda-estilo-personal',
    title: 'Mi estilo personal',
    category: 'moda',
    categoryLabel: 'Moda',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2', 'C1'],
    keywords: ['style', 'outfit', 'wardrobe', 'go-to', 'color palette', 'uniform'],
  },
  {
    id: 125,
    slug: 'moda-fast-fashion',
    title: 'Fast fashion',
    category: 'moda',
    categoryLabel: 'Moda',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['B1', 'B2', 'C1'],
    keywords: ['fast fashion', 'Shein', 'exploitation', 'cheap', 'throwaway', 'carbon'],
  },
  {
    id: 135,
    slug: 'kids-family',
    title: 'Mi familia',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'mini',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['mom', 'dad', 'brother', 'sister', 'grandma', 'grandpa'],
  },
  {
    id: 137,
    slug: 'kids-school',
    title: 'La escuela',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'junior',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['school', 'teacher', 'friend', 'class', 'lunch', 'recess'],
  },
  {
    id: 138,
    slug: 'kids-colors',
    title: 'Mis colores favoritos',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'mini',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['color', 'red', 'blue', 'yellow', 'green', 'purple'],
  },
  {
    id: 139,
    slug: 'kids-animals-farm',
    title: 'Animales de la granja y la selva',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'mini',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['animal', 'cow', 'dog', 'cat', 'lion', 'elephant'],
  },
  {
    id: 141,
    slug: 'kids-body',
    title: 'Mi cuerpo',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'mini',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['head', 'nose', 'eye', 'mouth', 'hand', 'foot'],
  },
  {
    id: 142,
    slug: 'kids-food-basic',
    title: 'Comidas ricas',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'mini',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['apple', 'bread', 'milk', 'rice', 'egg', 'banana'],
  },
  {
    id: 143,
    slug: 'kids-toy-unboxing',
    title: 'Abrir juguetes',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'mini',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['box', 'open', 'surprise', 'toy', 'gift', 'new'],
  },
  {
    id: 144,
    slug: 'kids-cartoons-heroes',
    title: 'Dibujitos y superhéroes',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'mini',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['hero', 'fast', 'strong', 'fly', 'save', 'funny'],
  },
  {
    id: 145,
    slug: 'kids-gaming-basic',
    title: 'Jugar en la pantalla',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'mini',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['play', 'jump', 'run', 'win', 'lose', 'level'],
  },
  {
    id: 146,
    slug: 'kids-treats',
    title: 'Comida divertida',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'mini',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['burger', 'fries', 'nuggets', 'popcorn', 'candy', 'ice cream'],
  },
  {
    id: 147,
    slug: 'kids-routine',
    title: 'Mi día de la mañana a la noche',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'junior',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['wake up', 'breakfast', 'lunch', 'dinner', 'bed', 'morning'],
  },
  {
    id: 148,
    slug: 'kids-house',
    title: 'Mi casa y mis habitaciones',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'junior',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['room', 'kitchen', 'bathroom', 'bedroom', 'house', 'garden'],
  },
  {
    id: 149,
    slug: 'kids-hobbies',
    title: 'Pasatiempos y deportes',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'junior',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['soccer', 'basketball', 'draw', 'music', 'play', 'swim'],
  },
  {
    id: 150,
    slug: 'kids-emotions',
    title: 'Cómo me siento',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'junior',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['happy', 'sad', 'angry', 'scared', 'excited', 'calm'],
  },
  {
    id: 151,
    slug: 'kids-nature',
    title: 'Naturaleza y dinosaurios',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'junior',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['forest', 'ocean', 'mountain', 'dinosaur', 'jungle', 'tree'],
  },
  {
    id: 152,
    slug: 'kids-youtube-challenges',
    title: 'Desafíos virales',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'junior',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['challenge', 'subscriber', 'viral', 'reaction', 'prank', 'video'],
  },
  {
    id: 153,
    slug: 'kids-sandbox-worlds',
    title: 'Mundos de bloques',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'junior',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['build', 'block', 'craft', 'mine', 'create', 'server'],
  },
  {
    id: 154,
    slug: 'kids-collecting',
    title: 'Coleccionar cartas y figuritas',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'junior',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['collection', 'trade', 'rare', 'common', 'card', 'figure'],
  },
  {
    id: 155,
    slug: 'kids-fast-food',
    title: 'Comida rápida y dulces',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'junior',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['combo', 'burger', 'fries', 'soda', 'ice cream', 'menu'],
  },
  {
    id: 156,
    slug: 'kids-entertainment',
    title: 'Música, pelis y series',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['song', 'movie', 'series', 'binge', 'favorite', 'playlist'],
  },
  {
    id: 157,
    slug: 'kids-travel',
    title: 'Viajes y culturas',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2'],
    keywords: ['travel', 'country', 'culture', 'language', 'city', 'trip'],
  },
  {
    id: 158,
    slug: 'kids-future-jobs',
    title: 'Trabajos del futuro',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['A2', 'B1', 'B2'],
    keywords: ['job', 'career', 'engineer', 'designer', 'scientist', 'creator'],
  },
  {
    id: 159,
    slug: 'kids-cooking',
    title: 'Cocinar y recetas',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['recipe', 'cook', 'bake', 'ingredient', 'taste', 'sweet'],
  },
  {
    id: 160,
    slug: 'kids-planet',
    title: 'Cuidar el planeta',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['recycle', 'pollution', 'climate', 'ocean', 'plastic', 'animal'],
  },
  {
    id: 161,
    slug: 'kids-opinions',
    title: 'Decir lo que pensás',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['A0', 'A1', 'A2', 'B1', 'B2'],
    keywords: ['think', 'agree', 'disagree', 'opinion', 'because', 'however'],
  },
  {
    id: 162,
    slug: 'kids-streaming',
    title: 'Streamers y transmisiones',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['live', 'stream', 'chat', 'follow', 'donate', 'clip'],
  },
  {
    id: 163,
    slug: 'kids-sneakers',
    title: 'Zapatillas y moda urbana',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['sneakers', 'drop', 'limited', 'outfit', 'style', 'fit'],
  },
  {
    id: 164,
    slug: 'kids-esports',
    title: 'Gaming pro y esports',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['team', 'tournament', 'rank', 'pro', 'competitive', 'strategy'],
  },
  {
    id: 165,
    slug: 'kids-slang',
    title: 'Slang y tendencias online',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['slang', 'trend', 'vibe', 'hype', 'flex', 'cringe'],
  },
  {
    id: 166,
    slug: 'open-chat',
    title: 'Charla abierta',
    category: 'general',
    categoryLabel: 'Charla libre',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    keywords: [],
  },
  {
    id: 177,
    slug: 'desarrollo-de-software-y-herramientas-ia',
    title: 'Desarrollo de software y herramientas IA',
    category: 'tech',
    categoryLabel: 'Tecnología',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['B1', 'B2', 'C1', 'C2'],
    keywords: ['framework', 'prompt', 'backend', 'syntax', 'deploy', 'repository'],
  },
  {
    id: 178,
    slug: 'diseno-y-construccion-del-hogar',
    title: 'Diseño y construcción del hogar',
    category: 'lifestyle',
    categoryLabel: 'Estilo de vida',
    audience: 'adult',
    segmento: 'adultos',
    levels: ['B1', 'B2', 'C1', 'C2'],
    keywords: ['layout', 'blueprint', 'space', 'renovation', 'contractor', 'budget'],
  },
  {
    id: 179,
    slug: 'juegos-de-pelea-y-torneos',
    title: 'Juegos de pelea y torneos',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'junior',
    levels: ['A1', 'A2'],
    keywords: ['combo', 'arena', 'block', 'health bar', 'tournament', 'character'],
  },
  {
    id: 180,
    slug: 'construccion-con-bloques-magicos',
    title: 'Construcción con bloques mágicos',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'mini',
    levels: ['A0', 'A1', 'A2'],
    keywords: ['block', 'build', 'tall', 'house', 'castle', 'break'],
  },
  {
    id: 181,
    slug: 'suscripciones-gaming-y-juego-en-la-nube',
    title: 'Suscripciones gaming y juego en la nube',
    category: 'videojuegos',
    categoryLabel: 'Videojuegos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['A1', 'A2', 'B1', 'B2'],
    keywords: ['cloud gaming', 'library', 'subscription', 'latency', 'cross-play', 'catalog'],
  },
  {
    id: 182,
    slug: 'quien-soy-y-quien-quiero-ser',
    title: 'Quién soy y quién quiero ser',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['B1', 'B2'],
    keywords: ['identity', 'comparison', 'pressure', 'authentic', 'confidence', 'insecure'],
  },
  {
    id: 183,
    slug: 'redes-sociales-el-lado-b',
    title: 'Redes sociales: el lado B',
    category: 'tech',
    categoryLabel: 'Tecnología',
    audience: 'kid',
    segmento: 'teen',
    levels: ['B1', 'B2'],
    keywords: ['algorithm', 'comparison', 'screen time', 'validation', 'burnout', 'filter'],
  },
  {
    id: 184,
    slug: 'crecer-en-un-mundo-que-cambia-rapido',
    title: 'Crecer en un mundo que cambia rápido',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['B1', 'B2'],
    keywords: ['change', 'uncertain', 'technology', 'generation', 'adapt', 'overwhelming'],
  },
  {
    id: 185,
    slug: 'causas-que-me-importan',
    title: 'Causas que me importan',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['B1', 'B2'],
    keywords: ['cause', 'awareness', 'injustice', 'activism', 'change', 'voice'],
  },
  {
    id: 186,
    slug: 'libertad-y-limites-con-mis-padres',
    title: 'Libertad y límites con mis padres',
    category: 'kids',
    categoryLabel: 'Para chicos',
    audience: 'kid',
    segmento: 'teen',
    levels: ['B1', 'B2'],
    keywords: ['curfew', 'trust', 'independence', 'rules', 'privacy', 'argument'],
  },
]
